export const spacing = {
  negativexs: '-0.4rem',
  xxxs: '0.07rem',
  xxs: '.2rem',
  xs: '.4rem',
  base: '.8rem',
  basePlusXs: '1.2rem',
  sm: '1.6rem',
  smPlusXs: '2rem',
  smPlusBasePlusxs: '2.8rem',
  md: '3.2rem',
  mdPlusXs: '3.6rem',
  mdPlusBase: '4rem',
  mdPlusSmPlusXs: '5.2rem',
  xl: '6.4rem',
  xlPlusBase: '7.2rem',
  xxxl: '8.8rem',
  cards: '15rem',
  photos: '25rem',
  maxWidth: '100%'
}
